// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"

	"github.com/gofrs/uuid"
)

type ImInventory struct {
	ID                  uuid.UUID    `json:"id"`
	InventoryName       string       `json:"inventory_name"`
	InventoryRfid       string       `json:"inventory_rfid"`
	ActualQty           string       `json:"actual_qty"`
	InventoryCategoryID uuid.UUID    `json:"inventory_category_id"`
	LogisticCenterID    uuid.UUID    `json:"logistic_center_id"`
	WarehouseID         uuid.UUID    `json:"warehouse_id"`
	LocationID          uuid.UUID    `json:"location_id"`
	CreatedAt           sql.NullTime `json:"created_at"`
	UpdatedAt           sql.NullTime `json:"updated_at"`
}

type ImInventoryCategory struct {
	ID                    uuid.UUID    `json:"id"`
	InventoryCategoryName string       `json:"inventory_category_name"`
	CreatedAt             sql.NullTime `json:"created_at"`
	UpdatedAt             sql.NullTime `json:"updated_at"`
}

type ImLocation struct {
	ID           uuid.UUID    `json:"id"`
	LocationName string       `json:"location_name"`
	WarehouseID  uuid.UUID    `json:"warehouse_id"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type ImLogisticCenter struct {
	ID                 uuid.UUID    `json:"id"`
	LogisticCenterName string       `json:"logistic_center_name"`
	CreatedAt          sql.NullTime `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
}

type ImWarehouse struct {
	ID               uuid.UUID    `json:"id"`
	WarehouseName    string       `json:"warehouse_name"`
	LogisticCenterID uuid.UUID    `json:"logistic_center_id"`
	CreatedAt        sql.NullTime `json:"created_at"`
	UpdatedAt        sql.NullTime `json:"updated_at"`
}
