// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"encoding/json"

	"github.com/gofrs/uuid"
)

type Querier interface {
	CountLogisticCenters(ctx context.Context) (int64, error)
	CountOfInventories(ctx context.Context, inventoryName string) (int64, error)
	CountOfInventoriesByAllFilters(ctx context.Context, arg CountOfInventoriesByAllFiltersParams) (int64, error)
	CountOfInventoriesByLocation(ctx context.Context, arg CountOfInventoriesByLocationParams) (int64, error)
	CountOfInventoriesByLogisticCenter(ctx context.Context, arg CountOfInventoriesByLogisticCenterParams) (int64, error)
	CountOfInventoriesByLogisticCenterAndLocation(ctx context.Context, arg CountOfInventoriesByLogisticCenterAndLocationParams) (int64, error)
	CountOfInventoriesByLogisticCenterAndWarehouse(ctx context.Context, arg CountOfInventoriesByLogisticCenterAndWarehouseParams) (int64, error)
	CountOfInventoriesByWarehouse(ctx context.Context, arg CountOfInventoriesByWarehouseParams) (int64, error)
	CountOfInventoriesByWarehouseAndLocation(ctx context.Context, arg CountOfInventoriesByWarehouseAndLocationParams) (int64, error)
	CountOfInventoryCategories(ctx context.Context) (int64, error)
	CountOfLocations(ctx context.Context) (int64, error)
	CountOfWarehouses(ctx context.Context) (int64, error)
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (ImInventory, error)
	CreateInventoryCategory(ctx context.Context, inventoryCategoryName string) (ImInventoryCategory, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (ImLocation, error)
	CreateLogisticCenter(ctx context.Context, logisticCenterName string) (ImLogisticCenter, error)
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (ImWarehouse, error)
	DeleteInventory(ctx context.Context, id uuid.UUID) error
	DeleteInventoryCategory(ctx context.Context, id uuid.UUID) error
	DeleteLocation(ctx context.Context, id uuid.UUID) error
	DeleteLogisticCenter(ctx context.Context, id uuid.UUID) error
	DeleteWarehouse(ctx context.Context, id uuid.UUID) error
	GetAllInventoriesData(ctx context.Context, arg GetAllInventoriesDataParams) ([]json.RawMessage, error)
	GetAllLogisticCenters(ctx context.Context) ([]json.RawMessage, error)
	GetInventories(ctx context.Context) ([]ImInventory, error)
	GetInventoriesByAllFilters(ctx context.Context, arg GetInventoriesByAllFiltersParams) ([]json.RawMessage, error)
	GetInventoriesByLocation(ctx context.Context, arg GetInventoriesByLocationParams) ([]json.RawMessage, error)
	GetInventoriesByLogisticCenter(ctx context.Context, arg GetInventoriesByLogisticCenterParams) ([]json.RawMessage, error)
	GetInventoriesByLogisticCenterAndLocation(ctx context.Context, arg GetInventoriesByLogisticCenterAndLocationParams) ([]json.RawMessage, error)
	GetInventoriesByLogisticCenterAndWarehouse(ctx context.Context, arg GetInventoriesByLogisticCenterAndWarehouseParams) ([]json.RawMessage, error)
	GetInventoriesByWarehouse(ctx context.Context, arg GetInventoriesByWarehouseParams) ([]json.RawMessage, error)
	GetInventoriesByWarehouseAndLocation(ctx context.Context, arg GetInventoriesByWarehouseAndLocationParams) ([]json.RawMessage, error)
	GetInventoryById(ctx context.Context, id uuid.UUID) (ImInventory, error)
	GetInventoryCategories(ctx context.Context) ([]ImInventoryCategory, error)
	GetInventoryCategoriesWithPagination(ctx context.Context, arg GetInventoryCategoriesWithPaginationParams) ([]ImInventoryCategory, error)
	GetInventoryCategoryById(ctx context.Context, id uuid.UUID) (ImInventoryCategory, error)
	GetInventoryCategoryByName(ctx context.Context, inventoryCategoryName string) (ImInventoryCategory, error)
	GetLocationById(ctx context.Context, id uuid.UUID) (json.RawMessage, error)
	GetLocationByName(ctx context.Context, locationName string) (ImLocation, error)
	GetLocationByWarehouseId(ctx context.Context, arg GetLocationByWarehouseIdParams) (ImLocation, error)
	GetLocations(ctx context.Context) ([]json.RawMessage, error)
	GetLocationsWithPagination(ctx context.Context, arg GetLocationsWithPaginationParams) ([]json.RawMessage, error)
	GetLogisticCenterById(ctx context.Context, id uuid.UUID) (json.RawMessage, error)
	GetLogisticCenterByName(ctx context.Context, logisticCenterName string) (ImLogisticCenter, error)
	GetLogisticCentersWithPagination(ctx context.Context, arg GetLogisticCentersWithPaginationParams) ([]json.RawMessage, error)
	GetOneInventoryData(ctx context.Context, id uuid.UUID) (json.RawMessage, error)
	GetOneLocation(ctx context.Context, id uuid.UUID) (ImLocation, error)
	GetOneLogisticCenterData(ctx context.Context, id uuid.UUID) (ImLogisticCenter, error)
	GetOneWarehouse(ctx context.Context, id uuid.UUID) (ImWarehouse, error)
	GetWarehouseById(ctx context.Context, id uuid.UUID) (json.RawMessage, error)
	GetWarehouseByLogisticCenterId(ctx context.Context, arg GetWarehouseByLogisticCenterIdParams) (ImWarehouse, error)
	GetWarehouseByName(ctx context.Context, warehouseName string) (ImWarehouse, error)
	GetWarehouses(ctx context.Context) ([]json.RawMessage, error)
	GetWarehousesWithPagination(ctx context.Context, arg GetWarehousesWithPaginationParams) ([]json.RawMessage, error)
	UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (ImInventory, error)
	UpdateInventoryCategory(ctx context.Context, arg UpdateInventoryCategoryParams) (ImInventoryCategory, error)
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) (ImLocation, error)
	UpdateLogisticCenter(ctx context.Context, arg UpdateLogisticCenterParams) (ImLogisticCenter, error)
	UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) (ImWarehouse, error)
}

var _ Querier = (*Queries)(nil)
